version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Kernel
          command: |
            git clone --depth 1 https://github.com/kutemeikito/android_kernel_xiaomi_ginkgo -b Fourteen && cd android_kernel_xiaomi_ginkgo && bash build.sh
